#Polars

###Считайте датасет из файла train.csv (это данные о выживаемости на Титанике) с помощью polars - 1 балл

In [35]:
import polars as pl
import numpy as np

In [36]:
from google.colab import drive
drive.mount("/content/drive")
df = pl.read_csv('/content/drive/MyDrive/train.csv')
df.head()

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

shape: (5, 12)
┌─────────────┬──────────┬────────┬───────────────────┬───┬───────────┬─────────┬───────┬──────────┐
│ PassengerId ┆ Survived ┆ Pclass ┆ Name              ┆ … ┆ Ticket    ┆ Fare    ┆ Cabin ┆ Embarked │
│ ---         ┆ ---      ┆ ---    ┆ ---               ┆   ┆ ---       ┆ ---     ┆ ---   ┆ ---      │
│ i64         ┆ i64      ┆ i64    ┆ str               ┆   ┆ str       ┆ f64     ┆ str   ┆ str      │
╞═════════════╪══════════╪════════╪═══════════════════╪═══╪═══════════╪═════════╪═══════╪══════════╡
│ 1           ┆ 0        ┆ 3      ┆ Braund, Mr. Owen  ┆ … ┆ A/5 21171 ┆ 7.25    ┆ null  ┆ S        │
│             ┆          ┆        ┆ Harris            ┆   ┆           ┆         ┆       ┆          │
│ 2           ┆ 1        ┆ 1      ┆ Cumings, Mrs.     ┆ … ┆ PC 17599  ┆ 71.2833 ┆ C85   ┆ C        │
│             ┆          ┆        ┆ John Bradley (Fl… ┆   ┆           ┆         ┆       ┆          │
│ 3           ┆ 1        ┆ 3      ┆ Heikkinen, Miss.  ┆ … ┆ STON/O2.  ┆ 7.925   ┆ null  ┆ S        │
│             ┆          ┆        ┆ Laina             ┆   ┆ 3101282   ┆         ┆       ┆          │
│ 4           ┆ 1        ┆ 1      ┆ Futrelle, Mrs.    ┆ … ┆ 113803    ┆ 53.1    ┆ C123  ┆ S        │
│             ┆          ┆        ┆ Jacques Heath (…  ┆   ┆           ┆         ┆       ┆          │
│ 5           ┆ 0        ┆ 3      ┆ Allen, Mr.        ┆ … ┆ 373450    ┆ 8.05    ┆ null  ┆ S        │
│             ┆          ┆        ┆ William Henry     ┆   ┆           ┆         ┆       ┆          │
└─────────────┴──────────┴────────┴───────────────────┴───┴───────────┴─────────┴───────┴──────────┘

###Выведите основную информацию о датасете: информацию о типах данных, число пропусков, средние значения и т.д. - 1 балл
hint: используйте методы и атрибуты датафрейма: describe(), dtypes, null_count(), mean()...

In [20]:
print("Типы данных")
print(df.dtypes)

print("Число пропусков в каждом столбце")
print(df.null_count())

print("Статистическое описание данных")
print(df.describe())

Типы данных
[Int64, Int64, Int64, String, String, Float64, Int64, Int64, String, Float64, String, String]
Число пропусков в каждом столбце
shape: (1, 12)
┌─────────────┬──────────┬────────┬──────┬───┬────────┬──────┬───────┬──────────┐
│ PassengerId ┆ Survived ┆ Pclass ┆ Name ┆ … ┆ Ticket ┆ Fare ┆ Cabin ┆ Embarked │
│ ---         ┆ ---      ┆ ---    ┆ ---  ┆   ┆ ---    ┆ ---  ┆ ---   ┆ ---      │
│ u32         ┆ u32      ┆ u32    ┆ u32  ┆   ┆ u32    ┆ u32  ┆ u32   ┆ u32      │
╞═════════════╪══════════╪════════╪══════╪═══╪════════╪══════╪═══════╪══════════╡
│ 0           ┆ 0        ┆ 0      ┆ 0    ┆ … ┆ 0      ┆ 0    ┆ 687   ┆ 2        │
└─────────────┴──────────┴────────┴──────┴───┴────────┴──────┴───────┴──────────┘
Статистическое описание данных
shape: (9, 13)
┌────────────┬─────────────┬──────────┬──────────┬───┬───────────┬───────────┬───────┬──────────┐
│ statistic  ┆ PassengerId ┆ Survived ┆ Pclass   ┆ … ┆ Ticket    ┆ Fare      ┆ Cabin ┆ Embarked │
│ ---        ┆ ---         ┆ ---      ┆ ---      ┆   ┆ ---       ┆ ---       ┆ ---   ┆ ---      │
│ str        ┆ f64         ┆ f64      ┆ f64      ┆   ┆ str       ┆ f64       ┆ str   ┆ str      │
╞════════════╪═════════════╪══════════╪══════════╪═══╪═══════════╪═══════════╪═══════╪══════════╡
│ count      ┆ 891.0       ┆ 891.0    ┆ 891.0    ┆ … ┆ 891       ┆ 891.0     ┆ 204   ┆ 889      │
│ null_count ┆ 0.0         ┆ 0.0      ┆ 0.0      ┆ … ┆ 0         ┆ 0.0       ┆ 687   ┆ 2        │
│ mean       ┆ 446.0       ┆ 0.383838 ┆ 2.308642 ┆ … ┆ null      ┆ 32.204208 ┆ null  ┆ null     │
│ std        ┆ 257.353842  ┆ 0.486592 ┆ 0.836071 ┆ … ┆ null      ┆ 49.693429 ┆ null  ┆ null     │
│ min        ┆ 1.0         ┆ 0.0      ┆ 1.0      ┆ … ┆ 110152    ┆ 0.0       ┆ A10   ┆ C        │
│ 25%        ┆ 224.0       ┆ 0.0      ┆ 2.0      ┆ … ┆ null      ┆ 7.925     ┆ null  ┆ null     │
│ 50%        ┆ 446.0       ┆ 0.0      ┆ 3.0      ┆ … ┆ null      ┆ 14.4542   ┆ null  ┆ null     │
│ 75%        ┆ 669.0       ┆ 1.0      ┆ 3.0      ┆ … ┆ null      ┆ 31.0      ┆ null  ┆ null     │
│ max        ┆ 891.0       ┆ 1.0      ┆ 3.0      ┆ … ┆ WE/P 5735 ┆ 512.3292  ┆ T     ┆ S        │
└────────────┴─────────────┴──────────┴──────────┴───┴───────────┴───────────┴───────┴──────────┘

###Посчитайте количество пассажиров каждого класса (Pclass) - 1 балл
hint: используйте методы: get_column(), value_counts()...

In [21]:
print("Количество пассажиров по классам")
print(df.get_column("Pclass").value_counts())

Количество пассажиров по классам
shape: (3, 2)
┌────────┬───────┐
│ Pclass ┆ count │
│ ---    ┆ ---   │
│ i64    ┆ u32   │
╞════════╪═══════╡
│ 1      ┆ 216   │
│ 2      ┆ 184   │
│ 3      ┆ 491   │
└────────┴───────┘

###Выведите количество выживших мужчин и женщин на корабле - 1 балл
hint: используйте методы: groupby(), agg(), pl.col(), sum()...

In [22]:
survived_by_sex = (
    df.group_by("Sex")
    .agg(pl.col("Survived").sum().alias("Выжившие"))
)
print("Количество выживших мужчин и женщин")
print(survived_by_sex)

Количество выживших мужчин и женщин
shape: (2, 2)
┌────────┬──────────┐
│ Sex    ┆ Выжившие │
│ ---    ┆ ---      │
│ str    ┆ i64      │
╞════════╪══════════╡
│ female ┆ 233      │
│ male   ┆ 109      │
└────────┴──────────┘

###Выведите часть таблицы с пассажирами, возраст которых больше 44 лет - 1 балл
hint: используйте методы: filter(), pl.col()...

In [23]:
older_passengers = df.filter(pl.col("Age") > 44)
print("Пассажиры старше 44 лет")
print(older_passengers)

Пассажиры старше 44 лет
shape: (115, 12)
┌─────────────┬──────────┬────────┬──────────────────┬───┬────────────┬─────────┬───────┬──────────┐
│ PassengerId ┆ Survived ┆ Pclass ┆ Name             ┆ … ┆ Ticket     ┆ Fare    ┆ Cabin ┆ Embarked │
│ ---         ┆ ---      ┆ ---    ┆ ---              ┆   ┆ ---        ┆ ---     ┆ ---   ┆ ---      │
│ i64         ┆ i64      ┆ i64    ┆ str              ┆   ┆ str        ┆ f64     ┆ str   ┆ str      │
╞═════════════╪══════════╪════════╪══════════════════╪═══╪════════════╪═════════╪═══════╪══════════╡
│ 7           ┆ 0        ┆ 1      ┆ McCarthy, Mr.    ┆ … ┆ 17463      ┆ 51.8625 ┆ E46   ┆ S        │
│             ┆          ┆        ┆ Timothy J        ┆   ┆            ┆         ┆       ┆          │
│ 12          ┆ 1        ┆ 1      ┆ Bonnell, Miss.   ┆ … ┆ 113783     ┆ 26.55   ┆ C103  ┆ S        │
│             ┆          ┆        ┆ Elizabeth        ┆   ┆            ┆         ┆       ┆          │
│ 16          ┆ 1        ┆ 2      ┆ Hewlett, Mrs.    ┆ … ┆ 248706     ┆ 16.0    ┆ null  ┆ S        │
│             ┆          ┆        ┆ (Mary D          ┆   ┆            ┆         ┆       ┆          │
│             ┆          ┆        ┆ Kingcome…        ┆   ┆            ┆         ┆       ┆          │
│ 34          ┆ 0        ┆ 2      ┆ Wheadon, Mr.     ┆ … ┆ C.A. 24579 ┆ 10.5    ┆ null  ┆ S        │
│             ┆          ┆        ┆ Edward H         ┆   ┆            ┆         ┆       ┆          │
│ 53          ┆ 1        ┆ 1      ┆ Harper, Mrs.     ┆ … ┆ PC 17572   ┆ 76.7292 ┆ D33   ┆ C        │
│             ┆          ┆        ┆ Henry Sleeper    ┆   ┆            ┆         ┆       ┆          │
│             ┆          ┆        ┆ (My…             ┆   ┆            ┆         ┆       ┆          │
│ …           ┆ …        ┆ …      ┆ …                ┆ … ┆ …          ┆ …       ┆ …     ┆ …        │
│ 858         ┆ 1        ┆ 1      ┆ Daly, Mr. Peter  ┆ … ┆ 113055     ┆ 26.55   ┆ E17   ┆ S        │
│             ┆          ┆        ┆ Denis            ┆   ┆            ┆         ┆       ┆          │
│ 863         ┆ 1        ┆ 1      ┆ Swift, Mrs.      ┆ … ┆ 17466      ┆ 25.9292 ┆ D17   ┆ S        │
│             ┆          ┆        ┆ Frederick Joel   ┆   ┆            ┆         ┆       ┆          │
│             ┆          ┆        ┆ (Ma…             ┆   ┆            ┆         ┆       ┆          │
│ 872         ┆ 1        ┆ 1      ┆ Beckwith, Mrs.   ┆ … ┆ 11751      ┆ 52.5542 ┆ D35   ┆ S        │
│             ┆          ┆        ┆ Richard Leonard… ┆   ┆            ┆         ┆       ┆          │
│ 874         ┆ 0        ┆ 3      ┆ Vander Cruyssen, ┆ … ┆ 345765     ┆ 9.0     ┆ null  ┆ S        │
│             ┆          ┆        ┆ Mr. Victor       ┆   ┆            ┆         ┆       ┆          │
│ 880         ┆ 1        ┆ 1      ┆ Potter, Mrs.     ┆ … ┆ 11767      ┆ 83.1583 ┆ C50   ┆ C        │
│             ┆          ┆        ┆ Thomas Jr (Lily  ┆   ┆            ┆         ┆       ┆          │
│             ┆          ┆        ┆ A…               ┆   ┆            ┆         ┆       ┆          │
└─────────────┴──────────┴────────┴──────────────────┴───┴────────────┴─────────┴───────┴──────────┘

#Ускорение работы с pandas

###Считайте датасет из файла train.csv (это данные о выживаемости на Титанике) с помощью pandas

In [43]:
import pandas as pd
import bottleneck as bn

In [62]:
df = pd.read_csv('/content/drive/MyDrive/train.csv', sep=',')
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

###Посчитайте средний возраст пассажиров и его стандартное отклонение с помощью bottleneck - 1 бал
hint: используйте методы: bn.nanmean(), bn.nanstd()

In [69]:
mean_age = bn.nanmean(df["Age"])
std_age = bn.nanstd(df["Age"])

print(f"Средний возраст пассажиров: {mean_age:.2f}")
print(f"Стандартное отклонение возраста: {std_age:.2f}")

Средний возраст пассажиров: 29.70
Стандартное отклонение возраста: 14.52

###Для каждого пассажира умножьте значение столбца Fare на 1.3 и сохраните результаты как новый столбец Fare_new - 1 балл
hint: используйте методы: .itertuples() или apply()

In [66]:
df["Fare_new"] = df["Fare"].apply(lambda x: x * 1.3)
display(df[["Fare", "Fare_new"]].head())

      Fare  Fare_new
0   7.2500   9.42500
1  71.2833  92.66829
2   7.9250  10.30250
3  53.1000  69.03000
4   8.0500  10.46500

#Оптимизация типов pandas

###Считайте датасет из файла Housing.csv (это данные о ценах домов) с помощью pandas

In [72]:
df = pd.read_csv('/content/drive/MyDrive/Housing.csv', sep=',')
df.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

###Для каждого столбца определите оптимальный с точки зрения потребления памяти тип данных - напишите свои выводы в комментариях - 2 балла

 "price": "int32",   Цена дома - целочисленный, можно уменьшить до int32

  "area": "int16",  #Площадь - целочисленный, можно уменьшить до int16

  "bedrooms": "int8",   В датасете 1-5 спален, int8 достаточно

  "bathrooms": "int8",   В датасете 1-3 ванных, int8 достаточно

  "stories": "int8",  Количество этажей - int8 достаточно    
  
  "mainroad": "category",   Категориальный признак (yes/no)

  "guestroom": "category",   Категориальный признак (yes/no)

   "basement": "category",   Категориальный признак (yes/no)

   "hotwaterheating": "category",   Категориальный признак (yes/no)

   "airconditioning": "category",   Категориальный признак (yes/no)

   "parking": "int8",   В датасете 0-3 парковочных мест, int8 достаточно

   "prefarea": "category",   Категориальный признак (yes/no)

   "furnishingstatus": "category"   Категориальный признак (semi/unfurnished/furnished)

###Поменяйте типы данных столбцов датафрейма на выбранные вами в прошлом пункте и сравните потребление памяти до и после оптимизации - 1 балл

In [74]:
%%timeit
df

15.3 ns ± 3.86 ns per loop (mean ± std. dev. of 7 runs, 100000000 loops each)

In [75]:
optimized_dtypes = {
    "price": "int32",
    "area": "int16",
    "bedrooms": "int8",
    "bathrooms": "int8",
    "stories": "int8",
    "mainroad": "category",
    "guestroom": "category",
    "basement": "category",
    "hotwaterheating": "category",
    "airconditioning": "category",
    "parking": "int8",
    "prefarea": "category",
    "furnishingstatus": "category"
}
df_optimized = df.astype(optimized_dtypes)

In [76]:
%%timeit
df_optimized

13.7 ns ± 2.22 ns per loop (mean ± std. dev. of 7 runs, 100000000 loops each)

Итого сэкономлено примерно 2 ns

###Другой способ определения эффективности оптимизации (по зптраченной памяти, а не времени выполнения)

In [73]:
optimized_dtypes = {
    "price": "int32",
    "area": "int16",
    "bedrooms": "int8",
    "bathrooms": "int8",
    "stories": "int8",
    "mainroad": "category",
    "guestroom": "category",
    "basement": "category",
    "hotwaterheating": "category",
    "airconditioning": "category",
    "parking": "int8",
    "prefarea": "category",
    "furnishingstatus": "category"
}

memory_before = df.memory_usage(deep=True).sum()
print(f"Потребление памяти до оптимизации: {memory_before / 1024:.2f} KB")

df_optimized = df.astype(optimized_dtypes)

memory_after = df_optimized.memory_usage(deep=True).sum()
print(f"Потребление памяти после оптимизации: {memory_after / 1024:.2f} KB")

print(f"Сэкономлено памяти: {(memory_before - memory_after) / 1024:.2f} KB")

Потребление памяти до оптимизации: 251.72 KB
Потребление памяти после оптимизации: 10.81 KB
Сэкономлено памяти: 240.91 KB